### ISSUE TITLE
Provisioning fails with error 429 on serverfarms

### ISSUE THREAD

**Issue by FrodeOA** [Microsoft/Partner-Smart-Office#1]
### Expected behavior

A provisioned resource of the type Microsoft.Web/serverfarms

### Actual behavior
Stops with error 429 with the message

{
  "Code": "Conflict",
  "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: 1f63d9ad-0d65-4f79-a864-0267d1be064b, OperationName: Create, CreatedTime: 4/5/2018 10:26:59 AM, RequestId: 619814e7-785f-468a-9848-8e9080813651, EntityType: 9",
  "Target": null,
  "Details": [
    {
      "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: 1f63d9ad-0d65-4f79-a864-0267d1be064b, OperationName: Create, CreatedTime: 4/5/2018 10:26:59 AM, RequestId: 619814e7-785f-468a-9848-8e9080813651, EntityType: 9"
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "59205",
        "MessageTemplate": "Cannot modify this web hosting plan because another operation is in progress. Details: {0}",
        "Parameters": [
          "Id: 1f63d9ad-0d65-4f79-a864-0267d1be064b, OperationName: Create, CreatedTime: 4/5/2018 10:26:59 AM, RequestId: 619814e7-785f-468a-9848-8e9080813651, EntityType: 9"
        ],
        "Code": "Conflict",
        "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: 1f63d9ad-0d65-4f79-a864-0267d1be064b, OperationName: Create, CreatedTime: 4/5/2018 10:26:59 AM, RequestId: 619814e7-785f-468a-9848-8e9080813651, EntityType: 9"
      }
    }
  ],
  "Innererror": null
}
### Steps to reproduce the problem
I tried to provision a new deployment in a new resource group

Also the variable cosmosDb needs to cosmosdb or fails on name validation

**Comment by isaiahwilliams** [comment]
Hi @FrodeOA, can you try the deployment again? I have corrected the template with #2 and perform test deployment.

**Comment by FrodeOA** [comment]
@isaiahwilliams it fails with the same error:

{
  "Code": "Conflict",
  "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: b18813bb-71d4-4c5a-a614-3b2176990cbd, OperationName: Create, CreatedTime: 4/6/2018 5:40:41 AM, RequestId: d5ee5d79-9e61-4fd1-b9d4-1fa16f790d93, EntityType: 9",
  "Target": null,
  "Details": [
    {
      "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: b18813bb-71d4-4c5a-a614-3b2176990cbd, OperationName: Create, CreatedTime: 4/6/2018 5:40:41 AM, RequestId: d5ee5d79-9e61-4fd1-b9d4-1fa16f790d93, EntityType: 9"
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "59205",
        "MessageTemplate": "Cannot modify this web hosting plan because another operation is in progress. Details: {0}",
        "Parameters": [
          "Id: b18813bb-71d4-4c5a-a614-3b2176990cbd, OperationName: Create, CreatedTime: 4/6/2018 5:40:41 AM, RequestId: d5ee5d79-9e61-4fd1-b9d4-1fa16f790d93, EntityType: 9"
        ],
        "Code": "Conflict",
        "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: b18813bb-71d4-4c5a-a614-3b2176990cbd, OperationName: Create, CreatedTime: 4/6/2018 5:40:41 AM, RequestId: d5ee5d79-9e61-4fd1-b9d4-1fa16f790d93, EntityType: 9"
      }
    }
  ],
  "Innererror": null
}

**Comment by isaiahwilliams** [comment]
I am glad to hear that this issue has been resolved. Thank you for helping with this.
