### ISSUE TITLE
Unable to get environmentsdata after running PullEnviornments

### ISSUE THREAD

**Issue by FrodeOA** [Microsoft/Partner-Smart-Office#21]
# Expected behavior
I'd expect it to populate or generate some data from running PullEnviornments and place it in the cosmodb under Environments but it's empty. If I run ProcessPartner after PullEnviornments I get an error saying:

parsedStack | [{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplateToken+ExpressionToken.Evaluate","level":0,"line":212,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\Path\\BindingTemplateToken.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplate.Bind","level":1,"line":112,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\Path\\BindingTemplate.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.DefaultResolutionPolicy.TemplateBind","level":2,"line":21,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\DefaultResolutionPolicy.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.TemplateBind","level":3,"line":361,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\AttributeCloner.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1+<>c__DisplayClass12_0.<GetTemplateResolver>b__0","level":4,"line":247,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\AttributeCloner.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1+<>c__DisplayClass6_2.<.ctor>b__10","level":5,"line":87,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\AttributeCloner.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.ResolveFromBindings","level":6,"line":347,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\AttributeCloner.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.ResolveFromBindingData","level":7,"line":291,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\AttributeCloner.cs"},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Bindings.BindingBase`1+<BindAsync>d__7.MoveNext","level":8,"line":49,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Bindings\\BindingBase.cs"},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":9,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":10,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":11,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","level":12,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1+<BindCoreAsync>d__8.MoveNext","level":13,"line":98,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Triggers\\TriggeredFunctionBinding.cs"}]
-- | --
  | outerId | 4581336
  | message | No value for named parameter 'PartnerCenterEndpoint'.
  | type | System.InvalidOperationException
  | id | 41736492
  | severityLevel | Error

outerId 4581336
message   No value for named parameter 'PartnerCenterEndpoint'.
type  System.InvalidOperationException
id 41736492
severityLevel Error

## Actual behavior

I'd expect it to populate some environment data and for it to run ProcessPartner to populate the database.

## Steps to reproduce the problem

Provision a fresh AAD app and a new resource group, run the ARM provisioning and manually start the PullEnviornments (this actually says success) and ProcessPartner functions. In my environment the AAD app and the resource group that contains the solutions are in two different tenants.

Some additional information:
The owner tenant of the AAD app enforces MFA on all members of the AdminAgents group, so i did some testing when running the following code from outside and inside trusted locations:

Get-Credential with username being the ApplicationId, password being ApplicationSecret

$creds = Get-Credential

$tenantID = {AAD App owner GUID}

Add-AzureRmAccount -Credential $creds -Tenant $tenantID -ServicePrincipal

From inside a trusted location:

Account          : appid
SubscriptionName : 
SubscriptionId   : 
TenantId         : {GUID of the AAD the App is in}
Environment      : AzureCloud

From outside a trusted location:

Account          : 
SubscriptionName : 
SubscriptionId   : 
TenantId         : 
Environment      :

**Comment by isaiahwilliams** [comment]
Hi @FrodeOA with this new deployment the environments collection is control through the newly introduced portal. You will need to browse to the web app that was deployed and create a new environment for the solution to work as designed. I will augment the code, so this is more obvious. Also, I am in the process of updating all the documentation today. That way you will have a guide that will help guide you through everything.

**Comment by FrodeOA** [comment]
So i provisioned a new instance and I can't access the configuration site, I assume I'm supposed to go to the non functions app  service URL but that just gives me this error: HTTP Error 502.5 - Process Failure

Also is the URL I entered when creating the AAD app used for anything?

**Comment by isaiahwilliams** [comment]
Hi @FrodeOA, that is good catch. After some debugging I discovered that the list permission was missing for the web app with respect to Azure Key Vault. You can correct this issue manually by modifying the access policies defined within Azure Key Vault. You will need to add the list permission for the service principal associated with your web application. The simplest way to do this is through the Azure portal by performing the following 

- Locate and open the instance of Azure Key Vault deployed by the ARM template 
- Under Settings click *Access policies* 
- Click on the application with the same name as your web app
- Add the *list* permission under the *Secret permissions* drop down
- Click Ok
- Click Save to commit these changes

Once you have performed this the web portal will load correctly. Pull request #40 contains a fix for this exact issue, so it will not happen with future deployments.

**Comment by FrodeOA** [comment]
Well now I have a new error:

Sign in
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application:

**Comment by isaiahwilliams** [comment]
Hi @FrodeOA, thank you for working with us to resolve all these issues. I have updated the FAQ to help address this issue and the others you might have. I would recommend that you check out the following entries 

[How do I fix AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application?](https://github.com/Microsoft/Partner-Smart-Office/wiki/FAQ#how-do-i-fix-aadsts50011-the-reply-url-specified-in-the-request-does-not-match-the-reply-urls-configured-for-the-application)
[Why do I receive an access denied message when attempting to access the portal?](https://github.com/Microsoft/Partner-Smart-Office/wiki/FAQ#why-do-i-receive-an-access-denied-message-when-attempting-to-access-the-portal)
[What should I do if the Partner Smart Office Admins role is missing?](https://github.com/Microsoft/Partner-Smart-Office/wiki/FAQ#what-should-i-do-if-the-partner-smart-office-admins-role-is-missing)

Please let me know if you have any other issues.

**Comment by FrodeOA** [comment]
So I tried to follow:
How do I fix AADSTS50011 and when adding http://.azurewebsites.net/signin-oidc to Reply URLs I get an error saying data validation error, if I enter http://*.azurewebsites.net/signin-oidc the website doesn't work and if I add the smart office URL it doesn't work. So what is the value supposed to be?

**Comment by isaiahwilliams** [comment]
Hi @FrodeOA, 

Are you still having issues?

**Comment by isaiahwilliams** [comment]
If you are still having trouble please feel free to reopen this issue.
