### ISSUE TITLE
SystemArgumentException in ProcessSecurity

### ISSUE THREAD

**Issue by kdmiddlebrooks** [Microsoft/Partner-Smart-Office#47]
# Steps to reproduce

Error appears every time the function runs.

## Expected behavior

Secure Score data would be extracted and stored in the DB

## Actual behavior

System.ArgumentException in ProcessSecurity appears in Application Insights. Secure Score data in the PowerBI file is empty, so I believe it's not retrieving the data (though it does retrieve the customer list and Azure storage information for the clients.

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

System.ArgumentException |   | System.ArgumentException at   Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable |   | Newtonsoft.Json, Version=11.0.0.0,   Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed | Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable | Microsoft.Azure.WebJobs.Host.FunctionInvocationException | Exception while executing function:   ProcessSecurity | System.Private.CoreLib, Version=4.0.0.0,   Culture=neutral, PublicKeyToken=7cec85d7bea7798e | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | System.ArgumentException | Could not cast or convert from   System.DateTime to Microsoft.Partner.SmartOffice.Models.Graph.CreatedDate.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
System.ArgumentException |   | System.ArgumentException at   Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable |   | Newtonsoft.Json, Version=11.0.0.0, Culture=neutral,   PublicKeyToken=30ad4fe6b2a6aeed | Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable | Microsoft.Azure.WebJobs.Host.FunctionInvocationException | Exception while executing function: ProcessSecurity | System.Private.CoreLib, Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | System.ArgumentException | Could not cast or convert from System.DateTime to   Microsoft.Partner.SmartOffice.Models.Graph.CreatedDate.

## Environment
Deployed into Azure directly from the master branch.

**Comment by isaiahwilliams** [comment]
Hi @kdmiddlebrooks, 

Thank you for opening this issue. I am investigating to see if I can reproduce the issue with my environment. I am hoping to have an update for you later today.

**Comment by isaiahwilliams** [comment]
Hi @kdmiddlebrooks, I have just pushed an update that includes a fix for this issue. This issue was caused by a change in the way the date was being returned from the Microsoft Graph. You can get this latest update by synchronizing your function app with the repository or redeploying it. Please feel free to re-open this issue if you have any additional questions regarding this bug.
