### ISSUE TITLE
deployment always failing on App Service Plan provisioning

### ISSUE THREAD

**Issue by ManuInNZ** [Microsoft/Partner-Smart-Office#6]
### Expected behavior
successful deployment of the ARM template

### Actual behavior
timeout and failure of the actual deployment.

### Steps to reproduce the problem
Used the azuredeploy.json either with the DeployTo Azure button of loading it as custom template
Failure is due to the App name I used ("Partner Smart Office") not being a valid App Service Plan name.

I would recommend to sanitize the name in the template or just reuse the ```uniquestring(resourceGroup().id)``` like for the other custom resources (assuming there is no issue of starting with a digit eventually).

Similar issue faced with the KeyVault, creating separate issue

Resource | Type | status
------------ | -------------|----------------
Partner Smart Office | Microsoft.Web/serverfarms | 429

Failing step status message
```
  "Code": "Conflict",
  "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: 227a93b8-b94b-49dc-993c-99f9d3f39c7d, OperationName: Create, CreatedTime: 5/3/2018 9:37:14 PM, RequestId: 21302aa0-ccbd-44cc-b9e4-270c3fb58587, EntityType: 9",
  "Target": null,
  "Details": [
    {
      "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: 227a93b8-b94b-49dc-993c-99f9d3f39c7d, OperationName: Create, CreatedTime: 5/3/2018 9:37:14 PM, RequestId: 21302aa0-ccbd-44cc-b9e4-270c3fb58587, EntityType: 9"
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "59205",
        "MessageTemplate": "Cannot modify this web hosting plan because another operation is in progress. Details: {0}",
        "Parameters": [
          "Id: 227a93b8-b94b-49dc-993c-99f9d3f39c7d, OperationName: Create, CreatedTime: 5/3/2018 9:37:14 PM, RequestId: 21302aa0-ccbd-44cc-b9e4-270c3fb58587, EntityType: 9"
        ],
        "Code": "Conflict",
        "Message": "Cannot modify this web hosting plan because another operation is in progress. Details: Id: 227a93b8-b94b-49dc-993c-99f9d3f39c7d, OperationName: Create, CreatedTime: 5/3/2018 9:37:14 PM, RequestId: 21302aa0-ccbd-44cc-b9e4-270c3fb58587, EntityType: 9"
      }
    }
  ],
  "Innererror": null
```

**Comment by isaiahwilliams** [comment]
@ManuInNZ thank you for this feedback. I have just published an update that includes some additional documentation. Please feel free to create a pull request to incorporate the changes you recommended above, or if you like I will be sure to include them in future release.

**Comment by isaiahwilliams** [comment]
@ManuInNZ with the latest commit I have implemented the changes you recommended. However, I have introduced a new web app that will be used to manage the environments. I will be updating the deployment documentation to help avoid this issue in the future.
