### ISSUE TITLE
KeyVault name not accepted

### ISSUE THREAD

**Issue by ManuInNZ** [Microsoft/Partner-Smart-Office#7]
### Expected behavior
Successful template deployment

### Actual behavior
```"keyVaultName": "[concat(uniquestring(resourceGroup().id), 'vault')]",``` returns an invalid name for a KeyVault
e.g.: 7paczw7bqb76yvault

### Steps to reproduce the problem
use "PartnerSmartOffice" as Resource Group name ? hoping that uniquestring returns a string with a leading digit.

proposed fix
```"keyVaultName": "[concat('vault',uniquestring(resourceGroup().id))]",```

**Comment by isaiahwilliams** [comment]
@ManuInNZ thank you for this feedback. I have incorporated the changes you recommended in the 0.0.2 release that was just published.
